---
- hosts: localhost
  connection: local
  tasks:
  - name: Create resource groupa
    azure_rm_resourcegroup:
      name: webserver_user7
      location: northeurope
    register: rg
  - debug:
      var: rg